import React, { useState, useMemo } from 'react';
import { AlertItem, AlertSeverity, AlertStatus } from '../../types/sensor';
import { StatusBadge } from '../common/StatusBadge';
import { formatTimestamp } from '../../utils/formatters';
import { 
  Bell, 
  AlertTriangle, 
  AlertCircle, 
  Info, 
  CheckCircle2, 
  Filter, 
  Search,
  Check
} from 'lucide-react';

export interface AlertsTabProps {
  alerts: AlertItem[];
  onAcknowledgeAlert: (alertId: string) => void;
  isDemo?: boolean;
}

export const AlertsTab: React.FC<AlertsTabProps> = ({
  alerts,
  onAcknowledgeAlert,
  isDemo = false
}) => {
  const [filterSeverity, setFilterSeverity] = useState<string>('all');
  const [filterStatus, setFilterStatus] = useState<string>('all');
  const [searchTerm, setSearchTerm] = useState<string>('');

  const filteredAlerts = useMemo(() => {
    return alerts.filter((a) => {
      if (filterSeverity !== 'all' && a.severity !== filterSeverity) return false;
      if (filterStatus !== 'all' && a.status !== filterStatus) return false;
      if (searchTerm) {
        const q = searchTerm.toLowerCase();
        const matchesSensor = a.sensor.toLowerCase().includes(q);
        const matchesMsg = a.message.toLowerCase().includes(q);
        const matchesId = a.id.toLowerCase().includes(q);
        if (!matchesSensor && !matchesMsg && !matchesId) return false;
      }
      return true;
    });
  }, [alerts, filterSeverity, filterStatus, searchTerm]);

  const activeCount = alerts.filter(a => a.status === 'ACTIVE').length;
  const criticalCount = alerts.filter(a => a.severity === 'CRITICAL').length;
  const warningCount = alerts.filter(a => a.severity === 'WARNING').length;

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-800 pb-4">
        <div>
          <div className="flex items-center gap-2">
            <h2 className="text-lg font-bold uppercase tracking-wider text-white">
              Prototype Safety Alerts & Threshold Triggers
            </h2>
            {isDemo && (
              <span className="rounded bg-amber-500/10 px-2 py-0.5 text-[10px] font-mono font-semibold text-amber-400 border border-amber-500/30">
                DEMO DATA
              </span>
            )}
          </div>
          <p className="text-xs text-slate-400">
            Real-time event log generated by the rule-based safety monitor
          </p>
        </div>

        {/* Severity counts pill */}
        <div className="flex items-center gap-2 text-xs font-mono">
          <span className="rounded-lg bg-rose-500/15 border border-rose-500/30 px-3 py-1 text-rose-400 font-bold">
            {criticalCount} Critical
          </span>
          <span className="rounded-lg bg-amber-500/15 border border-amber-500/30 px-3 py-1 text-amber-400 font-bold">
            {warningCount} Warning
          </span>
          <span className="rounded-lg bg-slate-800 border border-slate-700 px-3 py-1 text-slate-300 font-bold">
            {activeCount} Active
          </span>
        </div>
      </div>

      {/* Filter and Search Bar */}
      <div className="rounded-xl border border-slate-800 bg-industrial-900 p-4 shadow-sm">
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-3 text-xs font-mono">
          {/* Search */}
          <div className="relative">
            <Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-slate-500" />
            <input
              type="text"
              placeholder="Search alerts by sensor, message, or ID..."
              value={searchTerm}
              onChange={(e) => setSearchTerm(e.target.value)}
              className="w-full rounded border border-slate-700 bg-slate-950 pl-8 pr-3 py-2 text-slate-200 focus:outline-none focus:border-mine-cyan text-xs"
            />
          </div>

          {/* Filter Severity */}
          <div className="flex items-center gap-2">
            <label className="text-slate-400 text-[11px] whitespace-nowrap">Severity:</label>
            <select
              value={filterSeverity}
              onChange={(e) => setFilterSeverity(e.target.value)}
              className="w-full rounded border border-slate-700 bg-slate-950 p-2 text-slate-200 focus:outline-none focus:border-mine-cyan text-xs"
            >
              <option value="all">All Severities</option>
              <option value="CRITICAL">Critical Only</option>
              <option value="WARNING">Warning Only</option>
              <option value="INFO">Info Only</option>
            </select>
          </div>

          {/* Filter Status */}
          <div className="flex items-center gap-2">
            <label className="text-slate-400 text-[11px] whitespace-nowrap">Status:</label>
            <select
              value={filterStatus}
              onChange={(e) => setFilterStatus(e.target.value)}
              className="w-full rounded border border-slate-700 bg-slate-950 p-2 text-slate-200 focus:outline-none focus:border-mine-cyan text-xs"
            >
              <option value="all">All Statuses</option>
              <option value="ACTIVE">Active</option>
              <option value="ACKNOWLEDGED">Acknowledged</option>
              <option value="RESOLVED">Resolved</option>
            </select>
          </div>
        </div>
      </div>

      {/* Alerts Table */}
      <div className="rounded-xl border border-slate-800 bg-industrial-900 shadow-sm overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead className="bg-slate-950 text-slate-400 uppercase tracking-wider text-[10px] border-b border-slate-800">
              <tr>
                <th className="py-3 px-4">Alert ID</th>
                <th className="py-3 px-4">Timestamp</th>
                <th className="py-3 px-4">Rover ID</th>
                <th className="py-3 px-4">Sensor Origin</th>
                <th className="py-3 px-4">Measured Value</th>
                <th className="py-3 px-4">Threshold Breached</th>
                <th className="py-3 px-4">Severity</th>
                <th className="py-3 px-4">Status</th>
                <th className="py-3 px-4 text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-800/80 text-slate-300">
              {filteredAlerts.length === 0 ? (
                <tr>
                  <td colSpan={9} className="py-8 text-center text-slate-500 italic">
                    No alerts match the current filter selection.
                  </td>
                </tr>
              ) : (
                filteredAlerts.map((alert) => (
                  <tr
                    key={alert.id}
                    className={`transition-colors ${
                      alert.status === 'ACTIVE' && alert.severity === 'CRITICAL'
                        ? 'bg-rose-500/5 hover:bg-rose-500/10'
                        : alert.status === 'ACTIVE' && alert.severity === 'WARNING'
                        ? 'bg-amber-500/5 hover:bg-amber-500/10'
                        : 'hover:bg-slate-800/30'
                    }`}
                  >
                    <td className="py-3.5 px-4 font-bold text-mine-cyan flex items-center gap-1.5">
                      {alert.severity === 'CRITICAL' ? (
                        <AlertTriangle className="h-3.5 w-3.5 text-rose-400 shrink-0" />
                      ) : alert.severity === 'WARNING' ? (
                        <AlertCircle className="h-3.5 w-3.5 text-amber-400 shrink-0" />
                      ) : (
                        <Info className="h-3.5 w-3.5 text-sky-400 shrink-0" />
                      )}
                      <span>{alert.id}</span>
                    </td>
                    <td className="py-3.5 px-4 text-slate-400 whitespace-nowrap">
                      {formatTimestamp(alert.timestamp)}
                    </td>
                    <td className="py-3.5 px-4 font-semibold text-white">
                      {alert.rover_id}
                    </td>
                    <td className="py-3.5 px-4 text-slate-200">
                      <div>{alert.sensor}</div>
                      <div className="text-[10px] text-slate-400 font-normal">{alert.message}</div>
                    </td>
                    <td className="py-3.5 px-4 font-bold text-white">
                      {alert.value}
                    </td>
                    <td className="py-3.5 px-4 text-slate-400">
                      {alert.threshold}
                    </td>
                    <td className="py-3.5 px-4">
                      <StatusBadge status={alert.severity} size="sm" />
                    </td>
                    <td className="py-3.5 px-4">
                      <StatusBadge status={alert.status} size="sm" />
                    </td>
                    <td className="py-3.5 px-4 text-right">
                      {alert.status === 'ACTIVE' ? (
                        <button
                          onClick={() => onAcknowledgeAlert(alert.id)}
                          className="inline-flex items-center gap-1 rounded bg-slate-800 px-2.5 py-1 text-[11px] font-semibold text-slate-200 hover:bg-slate-700 hover:text-white transition-colors border border-slate-700"
                        >
                          <Check className="h-3 w-3 text-mine-gold" />
                          <span>Acknowledge</span>
                        </button>
                      ) : (
                        <span className="text-[11px] text-slate-400 italic">Acknowledged</span>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};
